export default {
  FONT_SIZE_SMALL: 12,
  FONT_SIZE_BODY: 16,
  FONT_SIZE_HEADLINE: 18,
  FONT_SIZE_TITLE: 26,
  FONT_SIZE_LARGE_TITLE: 48,
  FONT_WEIGHT_LIGHT: "200",
  FONT_WEIGHT_MEDIUM: "600",
  FONT_WEIGHT_HEAVY: "800",
  PRIMARY_TEXT_COLOR: "#FFF",
  SECONDARY_TEXT_COLOR: "#0A0617",
  TERTIARY_TEXT_COLOR: "#94949e",
  DESTRUCTIVE_COLOR: "#e71919",
  PRIMARY_BACKGROUND_COLOR: "#0A0617",
  SECONDARY_BACKGROUND_COLOR: "#16162D",
  SPACING: {
    SMALL: 8,
    MEDIUM: 16,
    LARGE: 32,
  },
  NUMBER_KEY_BUTTON: {
    SIZE: 80,
    CLEAR_BUTTON_SIZE: 60,
  },
  METRIC_TILE: {
    SIZE: 200,
  },
};
